/*  Houses of Westeros — data.js
    Single source of truth. No DOM dependency.                          */

const HOUSES = [
  { id:'stark',     name:'Stark',     words:'Winter is coming',           seat:'Winterfell',   region:'The North',          color:'#7e93a3' },
  { id:'targaryen', name:'Targaryen', words:'Fire and blood',             seat:'Dragonstone',  region:'Exiled / Valyrian',  color:'#b03040' },
  { id:'lannister', name:'Lannister', words:'Hear me roar',               seat:'Casterly Rock',region:'The Westerlands',    color:'#c0962a' },
  { id:'baratheon', name:'Baratheon', words:'Ours is the fury',           seat:"Storm's End",  region:'The Stormlands',     color:'#b07a20' },
  { id:'tyrell',    name:'Tyrell',    words:'Growing strong',             seat:'Highgarden',   region:'The Reach',          color:'#6a923e' },
  { id:'martell',   name:'Martell',   words:'Unbowed, unbent, unbroken',  seat:'Sunspear',     region:'Dorne',              color:'#c0722a' },
  { id:'greyjoy',   name:'Greyjoy',   words:'We do not sow',              seat:'Pyke',         region:'The Iron Islands',   color:'#4e6a6d' },
  { id:'arryn',     name:'Arryn',     words:'As high as honor',           seat:'The Eyrie',    region:'The Vale',           color:'#5a7fa0' },
  { id:'tully',     name:'Tully',     words:'Family, duty, honor',        seat:'Riverrun',     region:'The Riverlands',     color:'#8a3540' },
];

const PEOPLE = [
  // ── STARK ──────────────────────────────────────────────────────
  { id:'rickard-stark',  name:'Rickard Stark', house:'stark', title:'Lord of Winterfell', tier:1, status:'deceased',
    note:"Ned's father. Burned alive in the throne room by the Mad King — an act that helped ignite Robert's Rebellion.",
    tags:['rebellion'] },
  { id:'ned-stark', name:'Ned Stark', house:'stark', title:'Lord of Winterfell · Hand of the King', tier:2, status:'deceased',
    parents:['rickard-stark'], spouses:['catelyn-tully'],
    note:'Warden of the North. Beheaded for refusing to play the game dishonestly — the moment the show announces its rules.',
    tags:['hand','execution'] },
  { id:'lyanna-stark', name:'Lyanna Stark', house:'stark', title:"Ned's sister", tier:2, status:'deceased',
    parents:['rickard-stark'], spouses:['rhaegar-targaryen'],
    note:"Her secret relationship with Rhaegar Targaryen is the spark for Robert's Rebellion. Dies in childbirth — the child is Jon Snow.",
    tags:['secret','rebellion'] },
  { id:'catelyn-tully', name:'Catelyn Tully', house:'tully', title:'Lady of Winterfell', tier:2, status:'deceased',
    spouses:['ned-stark'],
    note:'From House Tully of Riverrun. Her marriage to Ned ties the riverlands to the North. Killed at the Red Wedding.',
    tags:[] },
  { id:'robb-stark', name:'Robb Stark', house:'stark', title:'King in the North', tier:3, status:'deceased',
    parents:['ned-stark','catelyn-tully'],
    note:"Crowned by northern lords after Ned's execution. Killed at the Red Wedding through Frey and Bolton treachery.",
    tags:['king','red wedding'] },
  { id:'sansa-stark', name:'Sansa Stark', house:'stark', title:'Queen in the North', tier:3, status:'alive',
    parents:['ned-stark','catelyn-tully'], spouses:['tyrion-lannister'],
    note:'Betrothed to Joffrey, forced to marry Tyrion Lannister, then Ramsay Bolton. Survives everything and rules the North.',
    tags:['survivor','marriage'] },
  { id:'arya-stark', name:'Arya Stark', house:'stark', title:'No One', tier:3, status:'alive',
    parents:['ned-stark','catelyn-tully'],
    note:'Trains as a Faceless Man assassin in Braavos. Ends the Night King. Goes her own way after the war.',
    tags:['assassin','night king'] },
  { id:'bran-stark', name:'Bran Stark', house:'stark', title:'King of the Six Kingdoms', tier:3, status:'alive',
    parents:['ned-stark','catelyn-tully'],
    note:'Pushed from a window early on. Becomes the Three-Eyed Raven, able to see all of history. Chosen king at the story\'s end.',
    tags:['king','three-eyed raven'] },
  { id:'rickon-stark', name:'Rickon Stark', house:'stark', title:"Ned's youngest son", tier:3, status:'deceased',
    parents:['ned-stark','catelyn-tully'],
    note:"The youngest Stark child. Killed by Ramsay Bolton's arrow in the Battle of the Bastards.",
    tags:[] },
  { id:'jon-snow', name:'Jon Snow', house:'stark', title:'Lord Commander · "King in the North"', tier:3, status:'alive',
    parents:['rhaegar-targaryen','lyanna-stark'],
    note:"Raised at Winterfell as Ned's bastard. Actually a Targaryen by blood — his real name is Aegon Targaryen.",
    tags:['secret','bastard','nights watch'] },

  // ── TARGARYEN ───────────────────────────────────────────────────
  { id:'aerys-targaryen', name:'Aerys II Targaryen', house:'targaryen', title:'"The Mad King"', tier:1, status:'deceased',
    note:'Increasingly cruel and paranoid. Overthrown by Robert Baratheon\'s rebellion; killed by his own Kingsguard, Jaime Lannister.',
    tags:['mad king','rebellion'] },
  { id:'rhaegar-targaryen', name:'Rhaegar Targaryen', house:'targaryen', title:'Crown Prince', tier:2, status:'deceased',
    parents:['aerys-targaryen'], spouses:['lyanna-stark'],
    note:"Heir to the throne. His secret marriage to Lyanna Stark sets off Robert's Rebellion. Killed by Robert at the Trident.",
    tags:['rebellion','secret'] },
  { id:'daenerys-targaryen', name:'Daenerys Targaryen', house:'targaryen', title:'"Mother of Dragons"', tier:2, status:'deceased',
    parents:['aerys-targaryen'],
    note:'Born in exile after the rebellion. Builds an army, hatches three dragons, and reclaims her family\'s seat — before it all unravels.',
    tags:['dragons','exile'] },

  // ── LANNISTER ───────────────────────────────────────────────────
  { id:'tywin-lannister', name:'Tywin Lannister', house:'lannister', title:'Lord of Casterly Rock', tier:1, status:'deceased',
    note:"Ruthless patriarch obsessed with legacy. The real power behind the throne once Joffrey sits it.",
    tags:['hand'] },
  { id:'cersei-lannister', name:'Cersei Lannister', house:'lannister', title:'Queen · Queen of the Seven Kingdoms', tier:2, status:'deceased',
    parents:['tywin-lannister'], spouses:['robert-baratheon','jaime-lannister'],
    note:"Married Robert Baratheon but secretly in love with her twin Jaime. Her children are Jaime's — the secret that drives the whole plot.",
    tags:['secret','queen'] },
  { id:'jaime-lannister', name:'Jaime Lannister', house:'lannister', title:'Ser · Kingsguard', tier:2, status:'deceased',
    parents:['tywin-lannister'], spouses:['cersei-lannister'],
    note:"Twin to Cersei, secretly her lover and the father of her children. Known as 'Kingslayer' for killing Aerys. Has a long redemption arc.",
    tags:['kingsguard','secret'] },
  { id:'tyrion-lannister', name:'Tyrion Lannister', house:'lannister', title:'"The Imp" · Hand', tier:2, status:'alive',
    parents:['tywin-lannister'], spouses:['sansa-stark'],
    note:"Sharp-witted and perpetually underestimated. Despised by his father. Becomes Daenerys's Hand and ends up shaping the final settlement.",
    tags:['hand','advisor'] },
  { id:'joffrey-baratheon', name:'Joffrey Baratheon', house:'lannister', title:'King', tier:3, status:'deceased',
    parents:['cersei-lannister','jaime-lannister'],
    note:"Sits the throne as Robert's son; actually Jaime's by Cersei. Cruel, petulant, poisoned at his own wedding.",
    tags:['king','secret'] },
  { id:'myrcella-baratheon', name:'Myrcella Baratheon', house:'lannister', title:'Princess', tier:3, status:'deceased',
    parents:['cersei-lannister','jaime-lannister'],
    note:"Sent to Dorne for an arranged betrothal. Kinder than her brothers. Poisoned on the journey home.",
    tags:['secret'] },
  { id:'tommen-baratheon', name:'Tommen Baratheon', house:'lannister', title:'King', tier:3, status:'deceased',
    parents:['cersei-lannister','jaime-lannister'],
    note:"Joffrey's gentler younger brother. Marries Margaery Tyrell. Takes his own life after Cersei destroys the Sept.",
    tags:['king','secret'] },

  // ── BARATHEON ───────────────────────────────────────────────────
  { id:'steffon-baratheon', name:'Steffon Baratheon', house:'baratheon', title:"Lord of Storm's End", tier:1, status:'deceased',
    note:'Father of Robert, Stannis, and Renly. Died at sea before the story begins.',
    tags:[] },
  { id:'robert-baratheon', name:'Robert Baratheon', house:'baratheon', title:'King of the Seven Kingdoms', tier:2, status:'deceased',
    parents:['steffon-baratheon'], spouses:['cersei-lannister'],
    note:'Won the throne through rebellion. Loved fighting; hated governing. Dies in a staged hunting accident in season one.',
    tags:['rebellion','king'] },
  { id:'stannis-baratheon', name:'Stannis Baratheon', house:'baratheon', title:'Lord of Dragonstone', tier:2, status:'deceased',
    parents:['steffon-baratheon'],
    note:'Rigid and joyless, but arguably the most rightful claimant once Joffrey\'s parentage is known. Burns his own daughter to appease a god.',
    tags:[] },
  { id:'renly-baratheon', name:'Renly Baratheon', house:'baratheon', title:"Lord of Storm's End", tier:2, status:'deceased',
    parents:['steffon-baratheon'],
    note:"Charming youngest brother. Claims the throne with Tyrell backing. Secretly in a relationship with Loras Tyrell. Killed by a shadow creature conjured by Melisandre.",
    tags:[] },

  // ── TYRELL ──────────────────────────────────────────────────────
  { id:'olenna-tyrell', name:'Olenna Tyrell', house:'tyrell', title:'"The Queen of Thorns"', tier:1, status:'deceased',
    note:'Grandmother and the true power of House Tyrell. Engineers Joffrey\'s poisoning herself. One of the great minds in the story.',
    tags:['poison'] },
  { id:'margaery-tyrell', name:'Margaery Tyrell', house:'tyrell', title:'Queen', tier:2, status:'deceased',
    parents:['olenna-tyrell'], spouses:['renly-baratheon','joffrey-baratheon','tommen-baratheon'],
    note:'Marries three kings in succession — Renly, Joffrey, then Tommen. Killed when Cersei blows up the Sept of Baelor.',
    tags:['marriage'] },
  { id:'loras-tyrell', name:'Loras Tyrell', house:'tyrell', title:'"The Knight of Flowers"', tier:2, status:'deceased',
    parents:['olenna-tyrell'], spouses:['renly-baratheon'],
    note:'Celebrated tournament knight, secretly Renly Baratheon\'s lover. Killed in the Sept explosion.',
    tags:[] },

  // ── MARTELL ─────────────────────────────────────────────────────
  { id:'doran-martell', name:'Doran Martell', house:'martell', title:'Prince of Dorne', tier:1, status:'deceased',
    note:'Cautious ruler who keeps Dorne neutral far longer than any other house. His patience is not rewarded.',
    tags:[] },
  { id:'oberyn-martell', name:'Oberyn Martell', house:'martell', title:'"The Red Viper"', tier:1, status:'deceased',
    note:"Doran's passionate brother. Seeks vengeance for his sister Elia's murder by the Mountain. Dies in a trial-by-combat.",
    tags:['duel'] },

  // ── GREYJOY ─────────────────────────────────────────────────────
  { id:'balon-greyjoy', name:'Balon Greyjoy', house:'greyjoy', title:'Lord of the Iron Islands', tier:1, status:'deceased',
    note:'Led a failed uprising against the Iron Throne years before the main story. Father of Theon and Yara.',
    tags:['rebellion'] },
  { id:'theon-greyjoy', name:'Theon Greyjoy', house:'greyjoy', title:"Ned Stark's Ward", tier:2, status:'deceased',
    parents:['balon-greyjoy'],
    note:"Raised at Winterfell as a hostage for his father's loyalty. Torn between houses his whole story. Dies defending Bran.",
    tags:['ward','redemption'] },
  { id:'yara-greyjoy', name:'Yara Greyjoy', house:'greyjoy', title:'Lady of the Iron Islands', tier:2, status:'alive',
    parents:['balon-greyjoy'],
    note:"Theon's older sister. Bold sea captain who contests the Iron Islands' rulership and aligns with Daenerys.",
    tags:[] },

  // ── ARRYN / TULLY ───────────────────────────────────────────────
  { id:'jon-arryn', name:'Jon Arryn', house:'arryn', title:'Hand of the King', tier:1, status:'deceased',
    spouses:['lysa-tully'],
    note:"Robert's first Hand of the King. His murder — disguised as natural death — is what pulls the Starks into King's Landing.",
    tags:['hand'] },
  { id:'lysa-tully', name:'Lysa Arryn', house:'arryn', title:'Lady of the Vale', tier:1, status:'deceased',
    spouses:['jon-arryn'],
    note:"Catelyn Stark's sister. Rules the Vale from the Eyrie — a mountain stronghold nearly impossible to take by force.",
    tags:[] },
];

const PEOPLE_BY_ID = Object.fromEntries(PEOPLE.map(function(p){ return [p.id, p]; }));
const HOUSES_BY_ID = Object.fromEntries(HOUSES.map(function(h){ return [h.id, h]; }));

const REVEALS = [
  { id:'jon-snow-parentage', from:'jon-snow',
    title:'Jon Snow is not a Stark by blood',
    body:'Raised at Winterfell as Ned\'s bastard, Jon is actually the son of Rhaegar Targaryen and Lyanna Stark — making him a Targaryen heir. His real name is Aegon Targaryen. His claim to the Iron Throne technically outranks Daenerys\'s. He is her nephew.',
    links:['rhaegar-targaryen','lyanna-stark','daenerys-targaryen','ned-stark'] },
  { id:'cersei-children', from:'joffrey-baratheon',
    title:"Cersei's children aren't Robert's",
    body:'Joffrey, Myrcella, and Tommen are all presented as Robert Baratheon\'s heirs — but they are biologically Jaime Lannister\'s, fathered in secret by Cersei\'s twin. This secret is the fuse that lights most of the show\'s political plotting.',
    links:['cersei-lannister','jaime-lannister','robert-baratheon'] },
];

const THRONE_ORDER = [
  { person:'aerys-targaryen',   note:'Overthrown by rebellion — the dynasty ended here' },
  { person:'robert-baratheon',  note:'Won the throne by force; reigned ~17 years' },
  { person:'joffrey-baratheon', note:'Robert\'s apparent son — actually Jaime\'s by Cersei' },
  { person:'tommen-baratheon',  note:'Joffrey\'s younger brother; same secret parentage' },
  { person:'cersei-lannister',  note:'Crowns herself after her children\'s deaths' },
  { person:'bran-stark',        note:'Chosen as king of the Six Kingdoms at the story\'s end' },
];

const VOCAB = [
  { category:'Titles & rank', terms:[
    { term:'Lord / Lady',        say:'ruler of land',       meaning:'A noble who governs a castle, town, or region under a king.',
      more:'Ned Stark is "Lord of Winterfell" — he rules the North under the king, the way a regional governor answers to a head of state.' },
    { term:'Hand of the King',   say:'chief advisor',       meaning:"The king's top minister; runs the kingdom day-to-day in the king's name.",
      more:'Think prime minister. Ned becomes Hand after Jon Arryn dies — which is what drags the Starks south into the capital\'s politics.' },
    { term:'Ward',               say:'a hosted child',      meaning:"A young noble raised in another lord's household for political reasons.",
      more:'Theon Greyjoy is Ned Stark\'s "ward" — officially a guest, really a hostage ensuring his family\'s loyalty.' },
    { term:'Maester',            say:'scholar-healer',      meaning:'A trained advisor who handles medicine, letters, and record-keeping for a house.',
      more:'Part doctor, part librarian, part secretary. Every great castle has one, identified by a chain worn around the neck showing their fields of study.' },
    { term:'Septon / Septa',     say:'priest / nun',        meaning:'Clergy of the Faith of the Seven, the main Westerosi religion.',
      more:'A septon leads worship; a septa often tutors noble girls in religion and manners.' },
    { term:'Master-at-arms',     say:'weapons trainer',     meaning:"The person responsible for training a household's fighters and young nobles in combat.",
      more:"Like a head coach for swordplay — who Arya and Bran train under at Winterfell before everything falls apart." },
  ]},
  { category:'Family & legitimacy', terms:[
    { term:'Bastard',            say:'born out of wedlock', meaning:"A child whose parents were not married — barred from inheriting titles or land by law.",
      more:'Bastards get region-specific surnames: "Snow" in the North, "Stone" in the Vale, "Sand" in Dorne, "Storm" in the stormlands, "Waters" near King\'s Landing. Jon\'s name marks his status, not a choice.' },
    { term:'Heir',               say:'next in line',        meaning:'The person legally next in line to inherit a title, estate, or throne.',
      more:'Usually the eldest legitimate son. When Robb dies without a clear heir, the Stark succession becomes dangerously complicated.' },
    { term:'Betrothed',          say:'engaged to marry',    meaning:'Formally promised in marriage, usually arranged for political advantage rather than affection.',
      more:'Sansa is betrothed to Joffrey to bind House Stark to House Lannister — a political arrangement neither teenager requested.' },
    { term:'Kinslayer',          say:'killer of family',    meaning:'Someone who has killed a blood relative — among the gravest taboos in Westerosi culture.',
      more:'Treated as worse than ordinary murder. Several character arcs hinge on whether someone will cross this line.' },
  ]},
  { category:'War & oaths', terms:[
    { term:'Sworn sword',        say:'a loyal fighter',     meaning:'A warrior formally pledged to protect a particular lord or house by oath.',
      more:'Not a mercenary — a sworn sword has taken an oath and is expected to hold it even at personal cost.' },
    { term:'Bannerman',          say:'a vassal lord',       meaning:'A lesser lord who owes military service and loyalty to a greater house.',
      more:'When Robb Stark calls his banners, it\'s these smaller northern lords who actually raise the armies for him.' },
    { term:'Kingsguard',         say:'royal bodyguards',    meaning:'An elite order of seven knights sworn for life to protect the king.',
      more:'Joining means surrendering land, titles, and the right to marry or father children. Jaime Lannister serves for most of the story.' },
    { term:"Night's Watch",      say:"guardians of the Wall", meaning:'A sworn brotherhood garrisoning the great ice Wall against threats from the north.',
      more:'Vow: "I shall take no wife, hold no lands, father no children." Where Jon Snow goes when bastards have nothing to inherit.' },
    { term:'Wildlings',          say:'free folk up north',  meaning:"People living beyond the Wall who acknowledge no southern king.",
      more:'They call themselves "free folk." The word "wildling" is the southerners\' dismissive label for them.' },
  ]},
  { category:'Address & honorifics', terms:[
    { term:'Ser',                say:'"sir"',                meaning:'The title of a knighted man — earned through ceremony, not birth.',
      more:'In-world spelling of "sir." Not every lord is a knight; not every knight is high-born. It\'s a separate honor.' },
    { term:'My lord / my lady',  say:'polite address',      meaning:'Standard respectful address for any noble, regardless of familiarity.',
      more:'Used even between friends in formal settings — it signals respect for the rank, not distance between the people.' },
    { term:'Your grace',         say:'address for a monarch', meaning:'The formal address when speaking directly to a reigning king or queen.',
      more:'Equivalent to "Your Majesty." Princes and princesses are "Your Highness." The distinction matters in throne-room scenes.' },
    { term:'Khaleesi',           say:'Dothraki queen',      meaning:'The wife of a khal, the warlord-chief of a Dothraki horse-clan.',
      more:'Daenerys earns this title by marrying Khal Drogo. It\'s specific to Dothraki culture — not a Westerosi word at all.' },
  ]},
];
